let games = [
    { name: "Asterigos", size: "8.6", price: 3000, image: "https://i.imgur.com/hNjm5oi.jpeg" },
    { name: "Assassins Creed Origins", size: "49.7", price: 3000, image: "https://i.imgur.com/8iPOFys.jpeg" },
    { name: "Assassins Creed Odyssey", size: "71.6", price: 3000, image: "https://i.imgur.com/VxSsJPa.jpeg" },
    { name: "Assassins Creed Valhalla", size: "48.2", price: 3000, image: "https://i.imgur.com/vDH15Bn.jpeg" },
    { name: "Assassins Creed Mirage", size: "35.2", price: 3000, image: "https://i.imgur.com/lVijwEu.jpeg" },
    { name: "Alien Isolation", size: "28.3", price: 3000, image: "https://i.imgur.com/FxM24uJ.jpeg" },
    { name: "A Plague Tale Innocence Arabic", size: "37.5", price: 3000, image: "https://i.imgur.com/p03QFLk.jpeg" },
    { name: "Battlefield 1 Arabic", size: "41.8", price: 3000, image: "https://i.imgur.com/PjGkBfz.jpeg" },
    { name: "Battlefield 4", size: "35.9", price: 3000, image: "https://i.imgur.com/coMsfl3.jpeg" },
    { name: "Battlefield V Arabic", size: "31.5", price: 3000, image: "https://i.imgur.com/gG9LMqy.jpeg" },
    { name: "Battlefield Hardline", size: "45.5", price: 3000, image: "https://i.imgur.com/sw5rCNb.jpeg" },
    { name: "Batman Arkham Knight", size: "46.6", price: 3000, image: "https://i.imgur.com/uELSRWt.jpeg" },
    { name: "BEN 10", size: "1.1", price: 3000, image: "https://i.imgur.com/OBA5nuO.jpeg" },
    { name: "Bloodborne", size: "31.7", price: 3000, image: "https://i.imgur.com/e50aA4V.jpeg" },
    { name: "Call Of Duty Advanced Warfare", size: "41.1", price: 3000, image: "https://i.imgur.com/Lg1HBpe.jpeg" },
    { name: "Call Of Duty Black Ops III", size: "43.5", price: 3000, image: "https://i.imgur.com/ixudEVm.jpeg" },
    { name: "Call Of Duty Black Ops Cold War", size: "166.7", price: 3000, image: "https://i.imgur.com/AAqhwWL.jpeg" },
    { name: "Call Of Duty Infinite Warfare", size: "47.3", price: 3000, image: "https://i.imgur.com/kytmjrZ.jpeg" },
    { name: "Call Of Duty Vanguard", size: "72.5", price: 3000, image: "https://i.imgur.com/ZImw4jF.jpeg" },
    { name: "Call Of Duty Modern Warfare", size: "94.8", price: 3000, image: "https://i.imgur.com/QmkOmbI.jpeg" },
    { name: "Call Of Duty Modern Warfare 2", size: "104.7", price: 3000, image: "https://i.imgur.com/Jvm1BpM.jpeg" },
    { name: "Call Of Duty Modern Warfare 3", size: "121.8", price: 3000, image: "https://i.imgur.com/BkCLImb.jpeg" },
    { name: "Call Of Duty Black Ops 6", size: "102.2", price: 3000, image: "https://i.imgur.com/jlEfeYK.jpeg" },
    { name: "Crash Bandicoot N. Sane Trilogy", size: "21.1", price: 3000, image: "https://i.imgur.com/KczMmOx.jpeg" },
    { name: "Crash Team Racing Nitro-Fueled", size: "12.7", price: 3000, image: "https://i.imgur.com/kFFaz0h.jpeg" },
    { name: "Dakar 18", size: "42.7", price: 3000, image: "https://i.imgur.com/QPizv1y.jpeg" },
    { name: "Dark Souls III", size: "26.8", price: 3000, image: "https://i.imgur.com/sLSru9e.jpeg" },
    { name: "Days Gone", size: "42.3", price: 3000, image: "https://i.imgur.com/ZGXHyzI.jpeg" },
    { name: "Death Stranding", size: "50.1", price: 3000, image: "https://i.imgur.com/re57kiZ.jpeg" },
    { name: "Devil May Cry 5", size: "45.2", price: 3000, image: "https://i.imgur.com/4Y71LYq.jpeg" },
    { name: "Detroit Become Human", size: "42.5", price: 3000, image: "https://i.imgur.com/TU2UPE7.jpeg" },
    { name: "Doom Eternal", size: "46.2", price: 3000, image: "https://i.imgur.com/sbmzPKl.jpeg" },
    { name: "Drive Club", size: "15.7", price: 3000, image: "https://i.imgur.com/Rf1jqtG.jpeg" },
    { name: "Dragon Ball Z Kakarot", size: "68.6", price: 3000, image: "https://i.imgur.com/YHshEvC.jpeg" },
    { name: "EA SPORTS FC 25", size: "44.1", price: 3000, image: "https://i.imgur.com/aPlrc54.jpeg" },
    { name: "Elden Ring", size: "57.4", price: 3000, image: "https://i.imgur.com/YbkBapv.jpeg" },
    { name: "Far Cry 4", size: "26.9", price: 3000, image: "https://i.imgur.com/seeK8fO.jpeg" },
    { name: "Far Cry 5", size: "46.0", price: 3000, image: "https://i.imgur.com/up4DIlK.jpeg" },
    { name: "Far Cry 6 Arabic", size: "36.7", price: 3000, image: "https://i.imgur.com/D7k8B2f.jpeg" },
    { name: "Fortnite", size: "17.5", price: 3000, image: "https://i.imgur.com/sH5Ee5A.jpeg" },
    { name: "Ghost of Tsushima Arabic", size: "48.6", price: 3000, image: "https://i.imgur.com/YQpd60k.jpeg" },
    { name: "God Of War Arabic", size: "40.1", price: 3000, image: "https://i.imgur.com/Sn7E8bD.jpeg" },
    { name: "God Of War Ragnarok Arabic", size: "122.3", price: 3000, image: "https://i.imgur.com/2VcPJox.jpeg" },
    { name: "God Of War® III Arabic", size: "36.7", price: 3000, image: "https://i.imgur.com/4bln5vL.jpeg" },
    { name: "God Of War 1", size: "7.1", price: 3000, image: "https://i.imgur.com/zufh5m2.jpeg" },
    { name: "Gran Turismo 7", size: "129.7", price: 3000, image: "https://i.imgur.com/7hneyfg.jpeg" },
    { name: "GTA III The Definitive Edition Arabic", size: "4.8", price: 3000, image: "https://i.imgur.com/nSREAxy.jpeg" },
    { name: "GTA San Andreas Definitive Edition Arabic", size: "21.3", price: 3000, image: "https://i.imgur.com/WnR5j8A.jpeg" },
    { name: "GTA Vice City The Definitive Edition Arabic", size: "10.3", price: 3000, image: "https://i.imgur.com/KcAbKXt.jpeg" },
    { name: "GTA V", size: "41.6", price: 3000, image: "https://i.imgur.com/cN4QDxp.jpeg" },
    { name: "High On Life", size: "40.3", price: 3000, image: "https://i.imgur.com/ZQ7J2Ua.jpeg" },
    { name: "Hogwarts Legacy", size: "70.4", price: 3000, image: "https://i.imgur.com/FLpcV3W.jpeg" },
    { name: "Hot Wheels Unleashed Turbocharged 2", size: "23.5", price: 3000, image: "https://i.imgur.com/bbIJVb8.jpeg" },
    { name: "Hollow Knight Arabic", size: "1.2", price: 3000, image: "https://i.imgur.com/oRKlAaS.jpeg" },
    { name: "Horizon Zero Dawn", size: "47.1", price: 3000, image: "https://i.imgur.com/fBJI3xa.jpeg" },
    { name: "Horizon Forbidden West", size: "89.6", price: 3000, image: "https://i.imgur.com/vCdP41I.jpeg" },
    { name: "It Takes Two", size: "37.1", price: 3000, image: "https://i.imgur.com/xAIh1OL.jpeg" },
    { name: "INSIDE Arabic", size: "1.3", price: 3000, image: "https://i.imgur.com/iFudJL8.jpeg" },
    { name: "Jumanji Wild Adventures", size: "5.0", price: 3000, image: "https://i.imgur.com/k5yhbFB.jpeg" },
    { name: "Jujutsu Kaisen Cursed Clash", size: "23.7", price: 3000, image: "https://i.imgur.com/d7GpqIk.jpeg" },
    { name: "Killzone Shadow Fall", size: "42.3", price: 3000, image: "https://i.imgur.com/JB0cp8i.jpeg" },
    { name: "Marvels Avengers", size: "67.0", price: 3000, image: "https://i.imgur.com/ac2EQJq.jpeg" },
    { name: "Marvels Guardians of The Galaxy", size: "83.1", price: 3000, image: "https://i.imgur.com/uW53uRJ.jpeg" },
    { name: "Midnight Fight Express", size: "5.0", price: 3000, image: "https://i.imgur.com/HZ2BIR1.jpeg" },
    { name: "Minecraft", size: "0.173", price: 3000, image: "https://i.imgur.com/gJBBAsA.jpeg" },
    { name: "Mortal Kombat X", size: "40.2", price: 3000, image: "https://i.imgur.com/etp14Km.jpeg" },
    { name: "Mortal Kombat 11", size: "68.3", price: 3000, image: "https://i.imgur.com/Q9QspAO.jpeg" },
    { name: "MX VS ATV LEGENDS", size: "26.3", price: 3000, image: "https://i.imgur.com/0i2FV5l.jpeg" },
    { name: "Need For Speed Heat", size: "42.6", price: 3000, image: "https://i.imgur.com/cGQlnWr.jpeg" },
    { name: "PES 2025", size: "45.4", price: 3000, image: "https://i.imgur.com/NKf9VDM.jpeg" },
    { name: "Prince Of Persia The Lost Crown", size: "10.3", price: 3000, image: "https://i.imgur.com/5lgKeJl.jpeg" },
    { name: "Ratchet & Clank", size: "27.5", price: 3000, image: "https://i.imgur.com/kclAk4H.jpeg" },
    { name: "Red Dead Redemption 1", size: "9.5", price: 3000, image: "https://i.imgur.com/bnmw5Zp.jpeg" },
    { name: "Red Dead Redemption 2", size: "106.1", price: 3000, image: "https://i.imgur.com/GnJCJxB.jpeg" },
    { name: "Resident Evil 2", size: "24.6", price: 3000, image: "https://i.imgur.com/uQRNqMR.jpeg" },
    { name: "Resident Evil 3", size: "22.4", price: 3000, image: "https://i.imgur.com/6sWrv7m.jpeg" },
    { name: "Resident Evil 4", size: "33.6", price: 3000, image: "https://i.imgur.com/shQDqqh.jpeg" },
    { name: "Resident Evil Village", size: "36.8", price: 3000, image: "https://i.imgur.com/1vPhpAG.jpeg" },
    { name: "Rise Of the Tomb Raider Arabic", size: "14.3", price: 3000, image: "https://i.imgur.com/zZnx41b.jpeg" },
    { name: "Riders Republic", size: "35.9", price: 3000, image: "https://i.imgur.com/huhQaY6.jpeg" },
    { name: "Sekiro Shadows Die Twice", size: "25.4", price: 3000, image: "https://i.imgur.com/ylG2qhr.jpeg" },
    { name: "SnowRunner", size: "23.1", price: 3000, image: "https://i.imgur.com/gRUqL85.jpeg" },
    { name: "Smurfs Kart", size: "2.2", price: 3000, image: "https://i.imgur.com/V5mcui4.jpeg" },
    { name: "Spider-Man Arabic", size: "40.3", price: 3000, image: "https://i.imgur.com/eutgZJy.jpeg" },
    { name: "Spider-Man Miles Morales Arabic", size: "53.1", price: 3000, image: "https://i.imgur.com/hPumimR.jpeg" },
    { name: "Shadow Of The Tomb Raider", size: "32.9", price: 3000, image: "https://i.imgur.com/CNWWLXs.jpeg" },
    { name: "Stray Arabic", size: "13.9", price: 3000, image: "https://i.imgur.com/9wgk9zw.jpeg" },
    { name: "Star Wars Jedi Fallen Order", size: "57.6", price: 3000, image: "https://i.imgur.com/QciaRoX.jpeg" },
    { name: "Street Fighter 6", size: "38.6", price: 3000, image: "https://i.imgur.com/ZI0lOTT.jpeg" },
    { name: "Tekken 7", size: "40.8", price: 3000, image: "https://i.imgur.com/MBhGgv1.jpeg" },
    { name: "The Callisto Protocol", size: "62.4", price: 3000, image: "https://i.imgur.com/GttLnIm.jpeg" },
    { name: "theHunter Call of The Wild", size: "54.1", price: 3000, image: "https://i.imgur.com/1BzAnO5.jpeg" },
    { name: "The Last Of Us Part 1 Arabic", size: "48.4", price: 3000, image: "https://i.imgur.com/WabgEIy.jpeg" },
    { name: "The Last Of Us Part 2 Arabic", size: "98.0", price: 3000, image: "https://i.imgur.com/WUrmG4K.jpeg" },
    { name: "Tomb Raider I-III Remastered", size: "5.8", price: 3000, image: "https://i.imgur.com/U5ge3CH.jpeg" },
    { name: "Truck Driver", size: "5.8", price: 3000, image: "https://i.imgur.com/0Nmd8My.jpeg" },
    { name: "The Witcher 3", size: "40.4", price: 3000, image: "https://i.imgur.com/sVvhIlb.jpeg" },
    { name: "Uncharted The Nathan Drake Collection Arabic", size: "43.5", price: 3000, image: "https://i.imgur.com/kJOyuMN.jpeg" },
    { name: "Uncharted 4 Thiefs End Arabic", size: "47.4", price: 3000, image: "https://i.imgur.com/LIozB6W.jpeg" },
    { name: "Uncharted The Lost Legacy Arabic", size: "47.8", price: 3000, image: "https://i.imgur.com/uUEjuAP.jpeg" },
    { name: "Until Dawn", size: "49.1", price: 3000, image: "https://i.imgur.com/ysidgIL.jpeg" },
    { name: "UFO Robot Grendizer", size: "8.5", price: 3000, image: "https://i.imgur.com/f86Fp9D.jpeg" },
    { name: "Valiant Hearts The Great War Arabic", size: "1.7", price: 3000, image: "https://i.imgur.com/tzXNu0q.jpeg" },
    { name: "Watch Dogs 2", size: "39.3", price: 3000, image: "https://i.imgur.com/9YzSMXS.jpeg" },
    { name: "Watch Dogs Legion", size: "54.2", price: 3000, image: "https://i.imgur.com/F7K8E1g.jpeg" },
    { name: "WRC Generations", size: "42.6", price: 3000, image: "https://i.imgur.com/OkRBAUG.jpeg" },
    { name: "WWE 2K 25", size: "82.6", price: 3000, image: "https://i.imgur.com/b69M6BF.jpeg" },

];

function scrollTop() {
    window.scrollTo({ top: 0, behavior: 'smooth' });
}

window.onscroll = function() {
    const scrollButton = document.querySelector('.scroll-top');
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        scrollButton.classList.add('visible');
    } else {
        scrollButton.classList.remove('visible');
    }
};

document.addEventListener('DOMContentLoaded', () => {
    renderGames(games);
});
